#
# Makefile for Aspen project
#
obj-$(CONFIG_HW_CROSSLAYER_OPT) += tcp_crosslayer.o
obj-$(CONFIG_HW_CROSSLAYER_OPT_DBG) = aspen_netlink.o

#
# Makefile for wifi Tcp-ipv4
#
obj-$(CONFIG_HW_WIFIPRO) += wifipro_tcp_monitor.o
obj-$(CONFIG_HW_WIFI) += wifi_tcp_statistics.o
