EXTRA_CFLAGS 	+= -Idrivers/hisi/mntn/blackbox/platform_lpm3
#LOCAL_C_INCLUDES += vendor/hisi/ap/libc_sec/include
#LOCAL_CFLAGS += -Ivendor/hisi/ap/libc_sec/include

obj-$(CONFIG_HISI_HISEE)  += hisi_hisee.o

