#drivers/input/touchscreen
#
#Makefile for the touch driver of Focaltech
#
	
obj-$(CONFIG_FTS_TS) += focaltech_core.o
obj-$(CONFIG_FTS_TS) += focaltech_i2c.o
obj-$(CONFIG_FTS_TS) += focaltech_flash.o	
#obj-$(CONFIG_FTS_TS) += focaltech_platform_data.o
#obj-$(CONFIG_FTS_TS) += focaltech_report.o
#obj-$(CONFIG_FTS_TS) += focaltech_auto_reset.o
#obj-$(CONFIG_FTS_TS) += focaltech_monitor.o
#obj-$(CONFIG_FTS_TS) += focaltech_gesture.o
#obj-$(CONFIG_FTS_TS) += focaltech_proximity.o
obj-$(CONFIG_FTS_TS) += focaltech_apk_node.o
obj-$(CONFIG_FTS_TS) += focaltech_sysfs.o
obj-$(CONFIG_FTS_TS) += focaltech_dts.o
#obj-$(CONFIG_FTS_TS) += focaltech_global/
obj-$(CONFIG_FTS_TS) += focaltech_test.o
