#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_HIDEEP_TS)  += ist520e.o
ist520e-objs := istxxxx_core_ops.o istxxxx_iface.o istxxxx_isp.o istxxxx_sysfs.o istxxxx_rawdata.o

