obj-$(CONFIG_HISI_HKADC) += adc/
obj-$(CONFIG_HISI_CCI_EXTRA)		+= cci_extra/
obj-$(CONFIG_HISI_CMDLINE_PARSE)	+= cmdline/
obj-$(CONFIG_HISI_IRQ_AFFINITY)	+= irq_affinity/
obj-$(CONFIG_HISILICON_PLATFORM_MAILBOX)	+= mailbox/
obj-$(CONFIG_HI6402_CODEC)			+= hi64xx/
obj-$(CONFIG_HI6403_CODEC)			+= hi64xx/
obj-$(CONFIG_HIFI_DSP_ONE_TRACK)		+= hifi_dsp/
obj-$(CONFIG_SOUND_TRIGGER)			+= soundtrigger/
obj-$(CONFIG_HIFI_MAILBOX)			+= hifi_mailbox/
obj-$(CONFIG_HISILICON_PLATFORM_MAINTAIN) += mntn/
obj-$(CONFIG_HISILICON_PLATFORM_KERNELDUMP) += memory_dump/
obj-$(CONFIG_HISILICON_PLATFORM_DDRC)   += ddrc/
obj-$(CONFIG_HISI_NOC)	+= noc/
obj-$(CONFIG_HISI_SYSCOUNTER) += hisi_syscounter/
obj-$(CONFIG_HISILICON_PLATFORM_SLIMBUS)+= slimbus/


obj-$(CONFIG_HI6402_HIFI_MISC) += hi64xx_dsp/
obj-$(CONFIG_HISI_HISEE) += hisee/
ifneq ($(strip $(CFG_HISI_OPENSOURCE)), true)
endif
obj-$(CONFIG_HISI_FLP)   += flp/
obj-$(CONFIG_HISI_IVP) += ivp/
obj-$(CONFIG_HISI_HISTAR_ISP) += isp/
obj-$(CONFIG_DRMDRIVER)                         += drmdriver/
obj-$(CONFIG_HI3XXX_EFUSE)                      += efuse/
obj-$(CONFIG_HISI_CMA)                          += hisi_cma/
obj-$(CONFIG_TZDRIVER)                          += tzdriver/
obj-$(CONFIG_LOAD_IMAGE) += load_image/
obj-$(CONFIG_HISI_SR)                      += pm/
obj-$(CONFIG_HISI_OCBC)                    += ocbc/
ifneq ($(link_kernel),false)
obj-$(CONFIG_HISI_BALONG_MODEM) += modem/
endif
obj-$(CONFIG_HISI_AXI) += axi/
obj-$(CONFIG_HISI_FLP)   += flp/
obj-$(CONFIG_HISI_HMPTH_SET) += hmpthresholds/
obj-$(CONFIG_HISI_PAGE_TRACKER) += hisi_page_tracker/
obj-$(CONFIG_HISI_PAGE_EXT) += hisi_page_ext/
obj-$(CONFIG_HISI_PERFHUB) += perfhub/
obj-$(CONFIG_HISI_HILOG) += hilog/
obj-$(CONFIG_HISI_TIMEKEEPER) += timekeeper/
obj-$(CONFIG_HISI_ARMV8_DEPRECATED) += armv8_deprecated/
obj-$(CONFIG_TLB_CONFLICT_WORKAROUND) += tlb_conflict/
