#
# Makefile for the memory technology device drivers.
#

# Core functionality.
-include $(srctree)/drivers/hisi/modem/config/product/$(OBB_PRODUCT_NAME)/config/balong_product_config.mk

obj-y				+= modem_dump_wdt.o
obj-y				+= modem_dump_base.o
obj-y				+= modem_dump_core.o
obj-y				+= modem_dump_etb.o
obj-y				+= modem_dump_apr.o
obj-y				+= modem_dump_area.o
obj-y				+= modem_dump_field.o
obj-y				+= modem_dump_hook.o
obj-y				+= modem_tlphy_tcm.o
obj-y				+= modem_cphy_tcm.o                   
subdir-ccflags-y := -Werror


