#
# Makefile for the Huawei root scanner.
#
# likun <quentin.lee@huawei.com>
#
# Copyright (c) 2001-2021, Huawei Tech. Co., Ltd. All rights reserved.
#

obj-$(CONFIG_HW_ROOT_SCAN) += hw_rscan_utils.o
obj-$(CONFIG_HW_ROOT_SCAN) += hw_rscan_proc.o
obj-$(CONFIG_HW_ROOT_SCAN) += kcode.o
obj-$(CONFIG_HW_ROOT_SCAN) += rproc.o
obj-$(CONFIG_HW_ROOT_SCAN) += sescan.o
obj-$(CONFIG_HW_ROOT_SCAN) += hw_rscan_scanner.o
obj-$(CONFIG_HW_ROOT_SCAN) += hw_rscan_data_uploader.o
obj-$(CONFIG_HW_ROOT_SCAN) += hw_rscan_module.o