# Makefile for the Huawei Kernel Harden.
#

obj-$(CONFIG_HUAWEI_KERNEL_STACK_NX) += kernel_harden/hw_stack_nx.o
obj-$(CONFIG_HUAWEI_KERNEL_MODULE_RANDOMIZE) += kernel_harden/hw_kaslr_module.o
obj-$(CONFIG_HUAWEI_KERNEL_STACK_RANDOMIZE) += kernel_harden/hw_kaslr_stack.o
obj-$(CONFIG_HUAWEI_KERNEL_STACK_RANDOMIZE_STRONG) += kernel_harden/hw_kaslr_stack_strong.o
