#ifndef __HI_BBP_LTEDRX_H__
#define __HI_BBP_LTEDRX_H__ 
#define HI_BBP_LTEDRX_WAKEUP_32K_CNT_OFFSET (0x1C)
#define HI_BBP_LTEDRX_SWITCH_32K_CNT_OFFSET (0x20)
#define HI_BBP_LTEDRX_SLEEP_START_OFFSET (0x28)
#define HI_BBP_LTEDRX_ARM_SLEEP_INT_MSK_OFFSET (0x40)
#define HI_BBP_LTEDRX_ARM_SLEEP_INT_CLEAR_OFFSET (0x44)
#define HI_BBP_LTEDRX_CLK_SWITCH_STATE_OFFSET (0x200)
#define HI_BBP_LTEDRX_SLP_TIME_CUR_OFFSET (0x20C)
#define HI_BBP_LTEDRX_ARM_INT_STATE_OFFSET (0x220)
#endif
