#ifndef __HI_BBP_TSTU_H__
#define __HI_BBP_TSTU_H__ 
#define HI_BBP_TSTU_SFN_OFT_OFFSET (0x14)
#define HI_BBP_LTEDRX_WAKEUP_32K_CNT_OFFSET (0x1C)
#define HI_BBP_LTEDRX_SWITCH_32K_CNT_OFFSET (0x20)
#define HI_BBP_TSTU_TIME_ADJ_START_OFFSET (0x24)
#define HI_BBP_TSTU_TDS_STU_SFN_OFFSET (0x204)
#endif
