#ifndef __HI_BBP_H__
#define __HI_BBP_H__ 
#include "mdrv_public.h"
#ifdef __cplusplus
extern "C" {
#endif
#define BBP_CHIP_HI3650 
typedef enum{
    BBP_PWR_COMM,
    BBP_PWR_IRM,
    BBP_PWR_UTX,
    BBP_PWR_WPS,
    BBP_PWR_LTE,
    BBP_PWR_G1,
    BBP_PWR_G2,
    BBP_PWR_BUTT
}BBP_PWR_ID_E;
typedef enum{
    BBP_CLK_AO,
    BBP_CLK_IRM_BBC245,
    BBP_CLK_IRM_TURBO,
    BBP_CLK_IRM_WBBP,
    BBP_CLK_TW_W122M,
    BBP_CLK_TW_W245M,
    BBP_CLK_TW_W61M,
    BBP_CLK_W122M,
    BBP_CLK_W245M,
    BBP_CLK_W61M,
    BBP_CLK_WAXI,
    BBP_CLK_WAXIM,
    BBP_CLK_TW_T122M,
    BBP_CLK_BUTT
}BBP_CLK_ID_E;
#define BBP_CLK_MIN BBP_CLK_AO
#define BBP_CLK_MAX BBP_CLK_TW_T122M
#define BBP_PWR_MIN BBP_PWR_COMM
#define BBP_PWR_MAX BBP_PWR_G2
#define BBP_VOTE_CLK_MIN BBP_CLK_IRM_BBC245
#define BBP_VOTE_CLK_MAX BBP_CLK_WAXIM
#define BBP_VOTE_PWR_MIN BBP_PWR_IRM
#define BBP_VOTE_PWR_MAX BBP_PWR_G2
#define BBP_PWC_MODULE_MIN PWC_COMM_MODULE_BBP_DRX
#define BBP_PWC_MODULE_MAX PWC_COMM_MODULE_BBP_MEM
#define BBP_PWC_MODEM_MIN PWC_COMM_MODEM_0
#define BBP_PWC_MODEM_MAX PWC_COMM_MODEM_2
#define BBP_PWC_MODE_MIN PWC_COMM_MODE_GSM
#define BBP_PWC_MODE_MAX PWC_COMM_MODE_CDMA_HRPD
#define BBP_PWR_NUM (BBP_PWR_MAX-BBP_PWR_MIN+1)
#define BBP_CLK_NUM (BBP_CLK_MAX-BBP_CLK_MIN+1)
#define BBP_VOTE_PWR_NUM (BBP_VOTE_PWR_MAX-BBP_VOTE_PWR_MIN+1)
#define BBP_VOTE_CLK_NUM (BBP_VOTE_CLK_MAX-BBP_VOTE_CLK_MIN+1)
#define BBP_MODULE_NUM (BBP_PWC_MODULE_MAX-BBP_PWC_MODULE_MIN+1)
#define BBP_MODEM_NUM (BBP_PWC_MODEM_MAX-BBP_PWC_MODEM_MIN+1)
#define BBP_MODE_NUM (BBP_PWC_MODE_MAX-BBP_PWC_MODE_MIN+1)
#define BBP_MAP_PWR_NUM BBP_VOTE_PWR_NUM
#define BBP_MAP_CLK_NUM BBP_VOTE_CLK_NUM
#define BBP_MODE_BUTT 7
#ifdef __cplusplus
}
#endif
#endif
