#ifndef __HI_BBP_DMA_H__
#define __HI_BBP_DMA_H__ 
#define BBP_DMA_BUSY_BIT_OFFSET 16
#define HI_BBP_FAST_CH0_BBP_ADDR_OFFSET 0x0a00
#define HI_BBP_FAST_CH0_SOC_ADDR_OFFSET 0x0a04
#define HI_BBP_FAST_CH0_CFG_OFFSET 0x0a08
#define HI_BBP_FAST_CH0_CTL_OFFSET 0x0a0c
#endif
