#ifndef __HI_MEMREPAIR_H__
#define __HI_MEMREPAIR_H__ 
#define MODEM_MEMREPAIR_DSP_BIT (7)
#define MODEM_MEMREPAIR_BBPIRM_BIT (5)
#define MODEM_MEMREPAIR_BBPCOM_BIT (4)
#define MODEM_MEMREPAIR_BBPCS_BIT (20)
#endif
