# Makefile for the DSM drivers.
#
# Each configuration option enables a list of files.
#obj-$(CONFIG_HUAWEI_BFM)  += boot_fail_hisi_interface.o
#obj-$(CONFIG_HUAWEI_BFM)  += boot_fail_monitor.o

obj-$(CONFIG_HUAWEI_BFM)  += boot_fail_hisi_interface.o
obj-$(CONFIG_HUAWEI_BFM)  += boot_fail_monitor.o
obj-$(CONFIG_HUAWEI_BFM)  += hw_boot_fail_core.o
obj-$(CONFIG_HUAWEI_BFM)  += hwboot_time_out.o
obj-y  += hwbfr/
