#ifndef __DDRTEST_GLOBAL_SRAM_MAP_H_
#define __DDRTEST_GLOBAL_SRAM_MAP_H_ 
#define DDRTEST_ACPU_LOG_BASE (HISI_SUB_RESERVED_FASTBOOT_LOG_PYHMEM_BASE)
#define DDRTEST_ACPU_LOG_SIZE (HISI_SUB_RESERVED_FASTBOOT_LOG_PYHMEM_SIZE)
#define PART_DDR_TEST_LOG (PART_HISITEST0)
#define PART_DDR_TEST_LOG_OFFSET (0)
#define PART_DDR_TEST_LPM3 (PART_HISITEST1)
#define PART_DDR_TEST_LPM3_OFFSET (0)
#define PART_DDR_TEST_IMAGE (PART_HISITEST2)
#define PART_DDR_TEST_IMAGE_OFFSET (0)
#endif
