obj-$(CONFIG_HISI_DEVFREQ)      += hisi_devfreq.o
obj-$(CONFIG_DEVFREQ_GOV_PM_QOS)    += governor_pm_qos.o
obj-$(CONFIG_HISI_DDR_DEVFREQ)      += ddr_devfreq.o
obj-$(CONFIG_DEVFREQ_GOV_MALI_ONDEMAND)      += governor_maliondemand.o

ccflags-$(CONFIG_HISI_DEVFREQ)  += -Idrivers/devfreq
