obj-$(CONFIG_SWITCH)        += switch/
obj-$(CONFIG_SWITCH_OTGID_GPIO)        += otg_gpio_switch/
obj-$(CONFIG_HUAWEI_TYPEC)        += typec/
obj-$(CONFIG_TCPC_CLASS)	+= pd/
obj-$(CONFIG_OTG_GPIO_ID)	+= otg_gpio_id/
