#=============================================================================
#  wifi
#=============================================================================

obj-$(CONFIG_HW_WIFI) += ipv4/

obj-$(CONFIG_HW_NETFILTER_MODULE) += hw_netfilter/

obj-$(CONFIG_HW_COMMSTAT) += commstat/
