#
# (C) COPYRIGHT 2012 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# A copy of the licence is included with the program, and can also be obtained
# from Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA  02110-1301, USA.
#
#


obj-$(CONFIG_MALI_PLATFORM_HI3650) += r12p1-04bet0/
obj-$(CONFIG_MALI_PLATFORM_HI6250) += r12p1-04bet0/
obj-$(CONFIG_MALI_PLATFORM_HI3660) += bifrost-r2p0-02dev0/
obj-$(CONFIG_MALI_PLATFORM_KIRIN970) += bifrost-r0p0-06rel0/
